env:
  browser: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: 
  no-console: 0
  # node es6 module imports require file extensions
  import/extensions:
    - error
    - always
    - ignorePackages: true
parser: babel-eslint
